src/Entity/Data/Player.php
<?php

namespace App\Entity\Data;

use App\Entity\Activity\Activity;
use App\Entity\Security\User;
use PennyPHP\Core\GameComponent\Entity\GameComponent;
use App\GameElement\Map\Component\MapComponent;
use App\GameElement\Mastery\MasterySet;
use App\GameElement\Position\Component\PositionComponent;
use App\Repository\Data\PlayerCharacterRepository;
use Attribute;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: PlayerCharacterRepository::class)]
#[UniqueEntity(fields: ['name'], message: 'This name is already taken.')]
#[ORM\UniqueConstraint(columns: ['name'])]
#[ORM\Table(name: "data_player_character")]
#[Attribute(Attribute::TARGET_CLASS)]
class Player extends GameComponent implements UserInterface
{
    #[ORM\Column(length: 50)]
    protected ?string $name = null;

    #[ORM\Column(type: 'json_document', nullable: true, options: ['jsonb' => true])]
    private MasterySet $masterySet;

    #[ORM\ManyToOne(inversedBy: 'playerCharacters')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;
    private array $roles = [];

    #[ORM\ManyToOne(targetEntity: Activity::class, cascade: ['all'])]
    #[ORM\JoinColumn(nullable: true)]
    private ?Activity $currentActivity;

    public function __construct()
    {
        $this->masterySet = new MasterySet();
        parent::__construct();
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): Player
    {
        $this->name = $name;

        return $this;
    }

    public function getMasteryExperience(string $masteryType): float
    {
        return $this->masterySet->getMastery($masteryType)->getExperience();
    }

    public function increaseMasteryExperience(string $masteryType, float $experience): static
    {
        $this->masterySet->increaseMasteryExperience($masteryType, $experience);

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function eraseCredentials(): void
    {
    }

    public function getUserIdentifier(): string
    {
        return $this->getName();
    }

    public function cloneMasterySet(): MasterySet
    {
        return $this->masterySet = clone $this->masterySet;
    }

    public function getMasterySet(): MasterySet
    {
        return ($this->masterySet ??= new MasterySet());
    }

    public function getCurrentActivity(): ?Activity
    {
        return $this->currentActivity;
    }

    public function startActivity(Activity $activity): void
    {
        $this->currentActivity = $activity;
    }

    public function endCurrentActivity(): void
    {
        $this->currentActivity = null;
    }

    public function isInvolvedInActivity(?Activity $activity = null): bool
    {
        if (!$this->currentActivity) {
            return false;
        }

        return $this->currentActivity === $activity;
    }

    public function getMap(): MapComponent
    {
        return $this->gameObject->getComponent(PositionComponent::class)->getPlaceId()->getComponent(MapComponent::class);
    }

    public function __serialize(): array
    {
        return [
            'id' => $this->id,
            'roles' => $this->roles,
            'name' => $this->name,
        ];
    }
}

templates/base.html.twig
<html lang="{{ app.locale }}">
    <head>
        <meta charset="UTF-8"/>
        <meta name="view-transition" content="same-origin" />
        <meta name="turbo-prefetch" content="false">
        <meta name="turbo-refresh-scroll" content="preserve">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}MMO Manager{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text><text y=%221.3em%22 x=%220.2em%22 font-size=%2276%22 fill=%22%23fff%22>sf</text></svg>">
        {% block stylesheets %}
            <link rel="stylesheet" href="{{ asset('fa-pro/css/all.min.css') }}">
            <link rel="stylesheet" href="{{ asset('styles/app.scss') }}">
        {% endblock %}

        {% block javascripts %}
            <script type="javascript" src="{{ asset('fa-pro/js/pro.min.js') }}"></script>
            {% block importmap %}{{ importmap('app') }}{% endblock %}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/layout.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <turbo-stream
            {{ custom_turbo_stream_listen('player_gui_' ~ app.user.id) }}
    ></turbo-stream>
    <div class="row h-100">
        <div class="col-auto position-relative">
            <div class="bg-dark h-100 px-1" id="sidebarLeft">
                <ul class="nav nav-leftline flex-column h-100 align-items-center">
                    <li class="nav-item w-100">{{ app.user.map.name|trans|upper }}</li>
                    <li class="nav-item mt-auto w-100">
                        <a class="h3 nav-link" href="{{ path('app_logout') }}">LOGOUT</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col">
            <div class="navbar navbar-expand-lg bg-dark position-sticky top-0" style="z-index: 2">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#user-navbar" aria-controls="user-navbar" aria-expanded="false" aria-label="Toggle navbar">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="user-navbar">
                    <div class="navbar-nav w-100">
                        <div class="nav-item">
                            {{ app.user.name }}
                        </div>
                        <div class="nav-item col-12 col-lg-3">
                            <turbo-frame id="player_health_{{ app.user.id }}">
                                {{ component('HealthBar', {gameObject: app.user.gameObject}) }}
                            </turbo-frame>
                        </div>
                        <div class="nav-item col-12 col-lg-3">
                            <turbo-frame id="player_current_activity">
                            </turbo-frame>
                        </div>
                        <div class="nav-item ms-auto col-12 col-lg-auto text-center">
                            <button class="btn btn-secondary" data-bs-toggle="collapse" data-bs-target="#inventory">Bag</button>
                        </div>
                        <div class="nav-item col-12 col-lg-auto text-center">
                            <button class="btn btn-secondary" data-bs-toggle="collapse" data-bs-target="#stats">Stats</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <turbo-frame id="page">
                        {% block main %}{% endblock %}
                    </turbo-frame>
                </div>
                <div class="col-auto">
                    <div class="position-sticky sticky-top">
                        <div id="inventory" class="collapse m-1">
                            {{ component('Backpack')}}
                            {% set bag = player.equipment %}
                            <div class="card">
                                <div class="card-header bg-info">
                                    {{ 'equipped items'|trans|capitalize }}
                                    <div>
                                        <turbo-frame class="progress" id="item_bag_fullness_{{ bag.id }}">
                                            <div class="progress-bar bg-primary" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: {{ bag.fullness*100 }}%;"></div>
                                        </turbo-frame>
                                    </div>
                                </div>
                                <turbo-frame class="card-body d-flex flex-wrap" id="item_bag_content_{{ bag.id }}" src="{{ path('app_itemBag_content', {id: bag.id}) }}" loading="lazy">
                                </turbo-frame>
                            </div>
                        </div>
                        <div id="stats" class="collapse m-1">
                            <div class="card">
                                <div class="card-header bg-info">
                                    <div class="position-absolute top-0 end-0">
                                        <button class="btn btn-sm btn-secondary" data-bs-toggle="collapse" data-bs-target="#stats">
                                            <span class="fas fa-times"></span>
                                            <span>{{ "Close"|trans }}</span>
                                        </button>
                                    </div>
                                    <div class="card-title">{{ "Stats"|trans }}</div>
                                </div>
                                <div class="card-body">
                                    <turbo-frame id="player-character-stats" loading="lazy" src="{{ path('playerCharacter_stats') }}"></turbo-frame>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <turbo-frame id="notifications" class="position-fixed bottom-0 end-0">
    </turbo-frame>
{% endblock %}